# Generated by Django 5.1.4 on 2025-03-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_course_photo_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(null=True, upload_to='courses/'),
        ),
    ]
