# Generated by Django 5.1.4 on 2025-03-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_alter_course_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/teachers/'),
        ),
    ]
